# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v1.10.6
_src_path: https://github.com/dafyddj/copier-docker-build
container_registry: docker.io
image_authors: SaltStack Formulas <GitHub @saltstack-formulas>
image_namespace: techneg
image_repo: ci-pre-commit
no_cache_filter: update
release_is_scheduled: true
repo_name: ci-pre-commit
repo_namespace: techneg-it
