# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v1.6.9 # __copier_update_needed v1.6.10
_src_path: gh:dafyddj/copier-docker-build
container_registry: docker.io
image_authors: SaltStack Formulas <GitHub @saltstack-formulas>
image_namespace: techneg
image_repo: ci-pre-commit
